# Generated by Django 5.2 on 2025-05-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraPagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Codigo',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Descripcion',
            new_name='descripcion',
        ),
    ]
