# Generated by Django 5.2 on 2025-05-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraPagina', '0002_rename_codigo_producto_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
